//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARYS_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acteur
    {
        public Acteur()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int IdActeur { get; set; }
        public string NomActeur { get; set; }
        public int IdRole { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
