//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARYS_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.LigneCommandes = new HashSet<LigneCommande>();
            this.LigneCommandeFournisseurs = new HashSet<LigneCommandeFournisseur>();
            this.LigneLivraisons = new HashSet<LigneLivraison>();
            this.Acteurs = new HashSet<Acteur>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int Reference { get; set; }
        public string LibelleArticle { get; set; }
        public double Prix { get; set; }
        public int IdGenre { get; set; }
        public Nullable<double> PrixFournisseur { get; set; }
        public int IdFournisseur { get; set; }
        public Nullable<bool> Reapprovisionnable { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual ICollection<LigneCommande> LigneCommandes { get; set; }
        public virtual ICollection<LigneCommandeFournisseur> LigneCommandeFournisseurs { get; set; }
        public virtual ICollection<LigneLivraison> LigneLivraisons { get; set; }
        public virtual StockArticle StockArticle { get; set; }
        public virtual ICollection<Acteur> Acteurs { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
