//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARYS_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandeFournisseur
    {
        public CommandeFournisseur()
        {
            this.LigneCommandeFournisseurs = new HashSet<LigneCommandeFournisseur>();
        }
    
        public int NumeroCommandeFournisseur { get; set; }
        public System.DateTime DateCommandeFournisseur { get; set; }
        public int IdFournisseur { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual ICollection<LigneCommandeFournisseur> LigneCommandeFournisseurs { get; set; }
    }
}
