//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARYS_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtatCommande
    {
        public EtatCommande()
        {
            this.PanierCommandes = new HashSet<PanierCommande>();
        }
    
        public int IdEtat { get; set; }
        public string LibelleEtat { get; set; }
    
        public virtual ICollection<PanierCommande> PanierCommandes { get; set; }
    }
}
