//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARYS_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int IdGenre { get; set; }
        public string LibelleGenre { get; set; }
        public int IdCategorie { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Categorie Categorie { get; set; }
    }
}
