//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARYS_BackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanierCommande
    {
        public PanierCommande()
        {
            this.LigneCommandes = new HashSet<LigneCommande>();
            this.Livraisons = new HashSet<Livraison>();
            this.Paiements = new HashSet<Paiement>();
        }
    
        public int NumeroCommande { get; set; }
        public System.DateTime DateCommande { get; set; }
        public int IdEtat { get; set; }
        public Nullable<int> IdPaiement { get; set; }
        public int NumeroClient { get; set; }
    
        public virtual EtatCommande EtatCommande { get; set; }
        public virtual ICollection<LigneCommande> LigneCommandes { get; set; }
        public virtual ICollection<Livraison> Livraisons { get; set; }
        public virtual ICollection<Paiement> Paiements { get; set; }
    }
}
